/*
 * generated by Xtext 2.14.0
 */
package duc.uminijava


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UMiniJavaStandaloneSetup extends UMiniJavaStandaloneSetupGenerated {

	def static void doSetup() {
		new UMiniJavaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
