/*
 * generated by Xtext 2.14.0
 */
package duc.uminijava


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UMiniJavaRuntimeModule extends AbstractUMiniJavaRuntimeModule {
}
