/**
 *
 * $Id$
 */
package uMiniJavaDynamicData.validation;

import duc.uminijava.uMiniJava.UTypeRef;

/**
 * A sample validator interface for {@link uMiniJavaDynamicData.UObjectInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UObjectInstanceValidator {
	boolean validate();

	boolean validateUType(UTypeRef value);
}
