<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uMiniJavaDynamicData" nsURI="http://www.uminijava.duc/UMiniJavaDynamicData"
    nsPrefix="uMiniJavaDynamicData">
  <eClassifiers xsi:type="ecore:EClass" name="UBooleanValue" eSuperTypes="../../org.tetrabox.minijava.semantics.modelstate/model/MiniJavaDynamicData.ecore#//BooleanValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIntegerValue" eSuperTypes="../../org.tetrabox.minijava.semantics.modelstate/model/MiniJavaDynamicData.ecore#//IntegerValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UDoubleValue" eSuperTypes="../../org.tetrabox.minijava.semantics.modelstate/model/MiniJavaDynamicData.ecore#//DoubleValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
