/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class duc_aintea_lib_poissonbinomial_Computer */

#ifndef _Included_duc_aintea_lib_poissonbinomial_Computer
#define _Included_duc_aintea_lib_poissonbinomial_Computer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     duc_aintea_lib_poissonbinomial_Computer
 * Method:    compute
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_duc_aintea_lib_poissonbinomial_Computer_compute
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
