/*
 * generated by Xtext 2.16.0
 */
package duc.uscript.ide

import com.google.inject.Guice
import duc.uscript.UScriptRuntimeModule
import duc.uscript.UScriptStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class UScriptIdeSetup extends UScriptStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new UScriptRuntimeModule, new UScriptIdeModule))
	}
	
}
