/*
 * generated by Xtext 2.16.0
 */
package duc.uscript


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UScriptStandaloneSetup extends UScriptStandaloneSetupGenerated {

	def static void doSetup() {
		new UScriptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
