/*
 * generated by Xtext 2.16.0
 */
package duc.uscript


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UScriptRuntimeModule extends AbstractUScriptRuntimeModule {
}
