/*
 * generated by Xtext 2.16.0
 */
package duc.uscript.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(UScriptInjectorProvider)
class UScriptParsingTest {
}
