/*
 * generated by Xtext 2.16.0
 */
package duc.uscript.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class UScriptWebModule extends AbstractUScriptWebModule {
}
