/*
 * generated by Xtext 2.16.0
 */
package duc.uscript.tests

//import com.google.inject.Inject
//import duc.uscript.uScript.Program
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
//import org.eclipse.xtext.testing.util.ParseHelper
//import org.junit.jupiter.api.Assertions
//import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(UScriptInjectorProvider)
class UScriptParsingTest {
//	@Inject
//	ParseHelper<Program> parseHelper
	
	// Disable to avoid re-generation by MWE2
//	@Test
//	def void loadModel() {
		//todo: Stop auto generation by MWE2
//	}
}
