/*
 * generated by Xtext 2.14.0
 */
package duc.uminijava.ide

import com.google.inject.Guice
import duc.uminijava.UMiniJavaRuntimeModule
import duc.uminijava.UMiniJavaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class UMiniJavaIdeSetup extends UMiniJavaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new UMiniJavaRuntimeModule, new UMiniJavaIdeModule))
	}
	
}
